//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolfPro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact_Setting
    {
        public int id { get; set; }
        public string first_Name { get; set; }
        public string last_Name { get; set; }
        public string Email { get; set; }
        public string Message { get; set; }
    }
}
