//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolfPro.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GolfProEntities : DbContext
    {
        public GolfProEntities()
            : base("name=GolfProEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<contact_Setting> contact_Setting { get; set; }
        public virtual DbSet<employee_Setting> employee_Setting { get; set; }
        public virtual DbSet<member_Setting> member_Setting { get; set; }
        public virtual DbSet<service_Setting> service_Setting { get; set; }
    }
}
